import { Metadata } from "next/types";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex  flex-col items-center justify-center h-screen bg-gray-950 text-slate-50 w-screen overflow-hidden">
        {children}
      </body>
    </html>
  );
}
